version: "3.9"

networks:
  twp:

volumes:
  db_data:
  wordpress_data:

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    container_name: twpdb
    networks:
      - twp

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    container_name: twpphpmyadmin
    networks:
      - twp

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      # ["./wordpress_data:/var/www/html"]
      - ./wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    container_name: twpwordpress
    networks:
      - twp

  vuejs:
    depends_on:
      - wordpress
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twpvuejs
    volumes:
      - ./MVVM_TWP:/app
    ports:
      - "8181:8181"
    networks:
      - twp
